### ISSUE TITLE
Build fails with following error when tests are enabled

### ISSUE THREAD

**Issue by vinayvishal** [eclipse-ee4j/orb-gmbal-pfl#9]
Master build job fails with following error when tests are enabled.

```bash
Running org.glassfish.pfl.basic.reflection.BridgeTest
Tests run: 42, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.317 sec
Running org.glassfish.pfl.basic.logex.WrapperGeneratorTest 
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.096 sec
Running org.glassfish.pfl.basic.algorithm.ObjectUtilityTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.531 sec <<< FAILURE!
whenObjectInJdk_displayFields(org.glassfish.pfl.basic.algorithm.ObjectUtilityTest)  Time elapsed: 0.53 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: a string containing "maxBytesPerChar=", "java.lang.Float", "3.0" in order
     but: was "org.apache.maven.surefire.report.ConsoleOutputCapture$ForwardingPrintStream<2012232625>(
    isStdout=java.lang.Boolean<754666084>(true)
    
    target=org.apache.maven.surefire.booter.ForkingRunListener<88558700>(
       at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.glassfish.pfl.basic.algorithm.ObjectUtilityTest.whenObjectInJdk_displayFields(ObjectUtilityTest.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

```

**Comment by russgold** [comment]
That test passes on Mac, which is where I developed it. It appears to be OS-specific, so in my pull request, I have now added a check for Linux, to bypass it.
